money_keeper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("money_keeper_app.urls")),
    path('admin/', admin.site.urls),
]

money_keeper_app/urls.py
from django.urls import path
from .views import dashboard, account_page, add_account, delete, upd_account, \
    income_list, add_income_type, show_income_types, upd_income_type, delete_income_type, \
    add_income, upd_income, delete_income, \
    expense_list, add_expense_type, show_expense_types, upd_expense_type, delete_expense_type, \
    add_expense, upd_expense, delete_expense
# from .views import dashboard

app_name = "money_keeper_app"

urlpatterns = [
    path("account/<int:pk>", account_page, name="account"),
    path("add_account/", add_account, name="add_account"),
    path("upd_account/<int:pk>", upd_account, name="upd_account"),
    path("delete/<int:pk>", delete, name="delete"),

    path("income_list/<int:pk>", income_list, name="income_list"),
    path("add_income/<int:pk>", add_income, name="add_income"),
    path("upd_income/<int:pk_account>/<int:pk_payment>", upd_income, name="upd_income"),
    path("delete_income/<int:pk_account>/<int:pk_payment>", delete_income, name="delete_income"),

    path("show_income_types/", show_income_types, name="show_income_types"),
    path("add_income_type/", add_income_type, name="add_income_type"),
    path("upd_income_type/<int:id>", upd_income_type, name="upd_income_type"),
    path("delete_income_type/<int:id>", delete_income_type, name="delete_income_type"),

    path("expense_list/<int:pk>", expense_list, name="expense_list"),
    path("add_expense/<int:pk>", add_expense, name="add_expense"),
    path("upd_expense/<int:pk_account>/<int:pk_payment>", upd_expense, name="upd_expense"),
    path("delete_expense/<int:pk_account>/<int:pk_payment>", delete_expense, name="delete_expense"),

    path("show_expense_types/", show_expense_types, name="show_expense_types"),
    path("add_expense_type/", add_expense_type, name="add_expense_type"),
    path("upd_expense_type/<int:id>", upd_expense_type, name="upd_expense_type"),
    path("delete_expense_type/<int:id>", delete_expense_type, name="delete_expense_type"),

    path("", dashboard, name="dashboard"),
]

money_keeper_app/forms.py
from django import forms
from .models import Account, Payment, IncomeType, ExpenseType


class NewAccountForm(forms.ModelForm):

    account_name = forms.CharField(
        required=True,
        widget=forms.widgets.TextInput(
            attrs={
                "placeholder": "Enter the name",
                "class": "input is-success is-normal",
            }
        ),
    )
    amount = forms.FloatField(
        required=True,
        widget=forms.widgets.NumberInput(
            attrs={
                "class": "input is-success is-normal",
            }
        ),
    )

    class Meta:
        model = Account
        exclude = ("user",)


class UpdAccountForm(forms.ModelForm):

    account_name = forms.CharField(
        required=True,
        widget=forms.widgets.TextInput(
            attrs={
                "placeholder": "Enter the name",
                "class": "input is-success is-normal",
            }
        ),
    )

    class Meta:
        model = Account
        fields = ["account_name"]


class NewIncomeTypeForm(forms.ModelForm):

    income_type = forms.CharField(
        required=True,
        widget=forms.widgets.TextInput(
            attrs={
                "placeholder": "Enter the type",
                "class": "input is-success is-normal",
            }
        ),
    )

    class Meta:
        model = IncomeType
        fields = ['income_type']


class UpdIncomeTypeForm(forms.ModelForm):

    income_type = forms.CharField(
        required=True,
        widget=forms.widgets.TextInput(
            attrs={
                "placeholder": "Enter the type",
                "class": "input is-success is-normal",
            }
        ),
    )

    class Meta:
        model = IncomeType
        fields = ['income_type']


class NewIncomeForm(forms.ModelForm):

    count = forms.FloatField(
        required=True,
        widget=forms.widgets.NumberInput(
            attrs={
                "class": " input is-info control ",
            }
        ),
    )

    income_type = forms.ModelChoiceField(
        required=True,
        widget=forms.widgets.Select(
            attrs={
                "class": " input is-info ",
            }
        ),
        queryset=IncomeType.objects.all()
    )

    class Meta:
        model = Payment
        fields = ["count"]


class UpdIncomeForm(forms.ModelForm):

    choices_list = [(obj.id, str(obj)) for obj in IncomeType.objects.all()]

    count = forms.FloatField(
        required=True,
        widget=forms.widgets.NumberInput(
            attrs={
                "class": " input is-info control ",
            }
        ),
    )

    income = forms.ModelChoiceField(
        required=True,
        widget=forms.widgets.Select(
            attrs={
                "class": " input is-info ",
            }
        ),
        queryset=IncomeType.objects.all()
    )

    class Meta:
        model = Payment
        fields = ["count", "income"]


class NewExpenseTypeForm(forms.ModelForm):

    expense_type = forms.CharField(
        required=True,
        widget=forms.widgets.TextInput(
            attrs={
                "placeholder": "Enter the type",
                "class": "input is-success is-normal",
            }
        ),
    )

    class Meta:
        model = ExpenseType
        fields = ['expense_type']


class UpdExpenseTypeForm(forms.ModelForm):
    expense_type = forms.CharField(
        required=True,
        widget=forms.widgets.TextInput(
            attrs={
                "placeholder": "Enter the type",
                "class": "input is-success is-normal",
            }
        ),
    )

    class Meta:
        model = ExpenseType
        fields = ['expense_type']


class NewExpenseForm(forms.ModelForm):

    count = forms.FloatField(
        required=True,
        widget=forms.widgets.NumberInput(
            attrs={
                "class": " input is-info control ",
            }
        ),
    )

    expense_type = forms.ModelChoiceField(
        required=True,
        widget=forms.widgets.Select(
            attrs={
                "class": " input is-info ",
            }
        ),
        queryset=ExpenseType.objects.all()
    )

    class Meta:
        model = Payment
        fields = ["count"]


class UpdExpenseForm(forms.ModelForm):

    choices_list = [(obj.id, str(obj)) for obj in ExpenseType.objects.all()]

    count = forms.FloatField(
        required=True,
        widget=forms.widgets.NumberInput(
            attrs={
                "class": " input is-info control ",
            }
        ),
    )

    expense = forms.ModelChoiceField(
        required=True,
        widget=forms.widgets.Select(
            attrs={
                "class": " input is-info ",
            }
        ),
        queryset=ExpenseType.objects.all()
    )

    class Meta:
        model = Payment
        fields = ["count", "expense"]

money_keeper_app/views.py
from django.shortcuts import render, redirect
from .forms import NewAccountForm, UpdAccountForm, \
    NewIncomeTypeForm, NewIncomeForm, UpdIncomeForm, UpdIncomeTypeForm, \
    NewExpenseTypeForm, NewExpenseForm, UpdExpenseForm, UpdExpenseTypeForm
from .models import Payment, Account, IncomeType, ExpenseType


# def dashboard(request):
#     return render(request, "base.html")
def dashboard(request):
    if not request.user.is_authenticated:
        # если неавторизован
        return render(request, "base.html")
    accounts = Account.objects.filter(user=request.user)
    if not accounts:
        # если у пользователя нет счетов
        return render(request, "base.html")
    return render(request, "money_keeper_app/accounts_list.html", {"accounts": accounts})


def delete(request, pk):
    account = Account.objects.get(pk=pk)
    account.delete()
    return redirect("money_keeper_app:dashboard")


def account_page(request, pk):
    if not request.user.is_authenticated:
        # если неавторизован
        return render(request, "base.html")
    account = Account.objects.get(pk=pk)
    payments = Payment.objects.filter(account=account.id).order_by("-created_at")
    return render(request, "money_keeper_app/account.html", {"account": account, "payments": payments})


def add_account(request):
    if not request.user.is_authenticated:
        # если неавторизован
        return render(request, "base.html")
    form = NewAccountForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        account = form.save(commit=False)
        account.user = request.user
        account.save()
        return redirect("money_keeper_app:dashboard")
    return render(request, "money_keeper_app/add_account.html", {"form": form})


def upd_account(request, pk):
    if not request.user.is_authenticated:
        # если неавторизован
        return render(request, "base.html")
    account_instance = Account.objects.get(pk=pk)
    form = UpdAccountForm(request.POST or None, instance=account_instance)
    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect("money_keeper_app:dashboard")
    return render(request, "money_keeper_app/upd_account.html", {"form": form})


def income_list(request, pk):
    if not request.user.is_authenticated:
        # если неавторизован
        return render(request, "base.html")
    account = Account.objects.get(pk=pk)
    incomes = Payment.objects.filter(account=account.id, payment_type="income").order_by("-created_at")
    return render(request, "money_keeper_app/income_list.html", {"account": account, "incomes": incomes})


def add_income_type(request):
    if not request.user.is_authenticated:
        # если неавторизован
        return render(request, "base.html")
    form = NewIncomeTypeForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        IncomeType.objects.create(
            income_type=form.cleaned_data['income_type']
        )
        return redirect("money_keeper_app:dashboard")
    return render(request, "money_keeper_app/add_income_type.html", {"form": form})


def show_income_types(request):
    if not request.user.is_authenticated:
        return render(request, "base.html")
    income_type_list = IncomeType.objects.all().order_by("income_type")
    return render(request, "money_keeper_app/show_income_types.html", {"income_type_list": income_type_list})


def upd_income_type(request, id):
    if not request.user.is_authenticated:
        # если неавторизован
        return render(request, "base.html")
    income_type_instance = IncomeType.objects.get(id=id)
    form = UpdIncomeTypeForm(request.POST or None, instance=income_type_instance)
    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect("money_keeper_app:show_income_types")
    return render(request, "money_keeper_app/upd_income_type.html", {"form": form})


def delete_income_type(request, id):
    if not request.user.is_authenticated:
        return render(request, "base.html")
    income_type = IncomeType.objects.get(id=id)
    income_type.delete()
    return redirect("money_keeper_app:show_income_types")


def add_income(request, pk):
    if not request.user.is_authenticated:
        return render(request, "base.html")

    if request.method == "POST":
        form = NewIncomeForm(request.POST)
        if form.is_valid():
            income_type = form.cleaned_data["income_type"]
            account = Account.objects.get(pk=pk)
            account.amount += form.cleaned_data['count']
            account.save()
            Payment.objects.create(
                account=Account.objects.get(pk=pk),
                payment_type="income",
                income=income_type,
                count=form.cleaned_data['count'],
                expense=None
            )
            return redirect("money_keeper_app:account", pk=pk)
    else:
        form = NewIncomeForm()
    return render(request, "money_keeper_app/add_income.html", {"form": form})


def upd_income(request, pk_account, pk_payment):
    if not request.user.is_authenticated:
        # если неавторизован
        return render(request, "base.html")
    income_instance = Payment.objects.get(pk=pk_payment)
    account = Account.objects.get(pk=pk_account)
    account.amount -= income_instance.count
    form = UpdIncomeForm(request.POST or None, instance=income_instance)
    if request.method == "POST" and form.is_valid():
        account.amount += form.cleaned_data['count']
        account.save()
        form.save()
        return redirect("money_keeper_app:account", pk=pk_account)
    return render(request, "money_keeper_app/upd_income.html", {"form": form})


def delete_income(request, pk_account, pk_payment):
    income = Payment.objects.get(pk=pk_payment)
    account = Account.objects.get(pk=pk_account)
    account.amount -= income.count
    account.save()
    income.delete()
    return redirect("money_keeper_app:account", pk=pk_account)


def expense_list(request, pk):
    if not request.user.is_authenticated:
        # если неавторизован
        return render(request, "base.html")
    account = Account.objects.get(pk=pk)
    expenses = Payment.objects.filter(account=account.id, payment_type="expense").order_by("-created_at")
    return render(request, "money_keeper_app/expense_list.html", {"account": account, "expenses": expenses})


def add_expense_type(request):
    if not request.user.is_authenticated:
        # если неавторизован
        return render(request, "base.html")
    form = NewExpenseTypeForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        ExpenseType.objects.create(
            expense_type=form.cleaned_data['expense_type']
        )
        return redirect("money_keeper_app:dashboard")
    return render(request, "money_keeper_app/add_expense_type.html", {"form": form})


def show_expense_types(request):
    if not request.user.is_authenticated:
        return render(request, "base.html")
    expense_type_list = ExpenseType.objects.all().order_by("expense_type")
    return render(request, "money_keeper_app/show_expense_types.html", {"expense_type_list": expense_type_list})


def upd_expense_type(request, id):
    if not request.user.is_authenticated:
        # если неавторизован
        return render(request, "base.html")
    expense_type_instance = ExpenseType.objects.get(id=id)
    form = UpdExpenseTypeForm(request.POST or None, instance=expense_type_instance)
    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect("money_keeper_app:show_expense_types")
    return render(request, "money_keeper_app/upd_expense_type.html", {"form": form})


def delete_expense_type(request, id):
    if not request.user.is_authenticated:
        return render(request, "base.html")
    expense_type = ExpenseType.objects.get(id=id)
    expense_type.delete()
    return redirect("money_keeper_app:show_expense_types")


def add_expense(request, pk):
    if not request.user.is_authenticated:
        return render(request, "base.html")

    if request.method == "POST":
        form = NewExpenseForm(request.POST)
        if form.is_valid():
            expense_type = form.cleaned_data["expense_type"]
            account = Account.objects.get(pk=pk)
            account.amount -= form.cleaned_data['count']
            account.save()
            Payment.objects.create(
                account=Account.objects.get(pk=pk),
                payment_type="expense",
                income=None,
                count=form.cleaned_data['count'],
                expense=expense_type
            )
            return redirect("money_keeper_app:account", pk=pk)
    else:
        form = NewExpenseForm()
    return render(request, "money_keeper_app/add_expense.html", {"form": form})


def upd_expense(request, pk_account, pk_payment):
    if not request.user.is_authenticated:
        # если неавторизован
        return render(request, "base.html")
    expense_instance = Payment.objects.get(pk=pk_payment)
    account = Account.objects.get(pk=pk_account)
    account.amount += expense_instance.count
    form = UpdExpenseForm(request.POST or None, instance=expense_instance)
    if request.method == "POST" and form.is_valid():
        account.amount -= form.cleaned_data['count']
        account.save()
        form.save()
        return redirect("money_keeper_app:account", pk=pk_account)
    return render(request, "money_keeper_app/upd_expense.html", {"form": form})


def delete_expense(request, pk_account, pk_payment):
    expense = Payment.objects.get(pk=pk_payment)
    account = Account.objects.get(pk=pk_account)
    account.amount += expense.count
    account.save()
    expense.delete()
    return redirect("money_keeper_app:account", pk=pk_account)

money_keeper_app/templates/money_keeper_app/account.html
{% extends 'base.html' %}

{% block content %}

<div class="column">
    <div class="block">
        <div class="card">
            <div class="card-content">
                <div class="columns">
                    <div class="column">
                        <div class="media">
                            <div class="media-content">
                                <p class="title is-5">
                                    Account: {{ account.account_name }}
                                </p>
                                <p class="title is-6">
                                    Amount: {{ account.amount }}
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="column">
                        <a href="{% url 'money_keeper_app:upd_account' account.id %}">
                            <button class="button is-info ">
                                Update
                            </button>
                        </a>
                        <a href="{% url 'money_keeper_app:add_income'  account.id %}">
                            <button class="button is-info ">
                                Add income
                            </button>
                        </a>
                        <a href="{% url 'money_keeper_app:add_expense'  account.id %}">
                            <button class="button is-info ">
                                Add expense
                            </button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="block">
        {% for payment in payments %}
            <div class="card">
                <div class="card-content">
                    <div class="media">
                        <div class="media-content">
                            {% if payment.payment_type == 'income' %}
                                <div class="columns">
                                    <div class="column">
                                        <p class="title is-5">
                                            Income: +{{ payment.count }} ({{payment.created_at}})
                                        </p>
                                        <p class="title is-6">
                                            {{ payment.income }}
                                        </p>
                                    </div>
                                    <div class="column">
                                        <a href="{% url 'money_keeper_app:upd_income' account.id payment.pk %}">
                                            <button class="button is-info ">
                                                Update income
                                            </button>
                                        </a>
                                        <a href="{% url 'money_keeper_app:delete_income' account.id payment.pk %}">
                                            <button class="button is-info ">
                                                Delete income
                                            </button>
                                        </a>
                                    </div>
                                </div>
                            {% else %}
                                <div class="columns">
                                    <div class="column">
                                        <p class="title is-5">
                                            Expense: -{{ payment.count }} ({{payment.created_at}})
                                        </p>
                                        <p class="title is-6">
                                            {{ payment.expense }}
                                        </p>
                                    </div>
                                    <div class="column">
                                        <a href="{% url 'money_keeper_app:upd_expense' account.id payment.pk %}">
                                            <button class="button is-info ">
                                                Update expense
                                            </button>
                                        </a>
                                        <a href="{% url 'money_keeper_app:delete_expense'  account.id payment.pk %}">
                                            <button class="button is-info ">
                                                Delete expense
                                            </button>
                                        </a>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

<div class="column is-one-third">
    <div class="box">
        <div class="block">
            <a href="{% url 'money_keeper_app:account' account.id %}">
                <button class="button is-info is-outlined is-fullwidth">
                    All payments
                </button>
            </a>
        </div>
        <div class="block">
            <a href="{% url 'money_keeper_app:income_list' account.id %}">
                <button class="button is-info is-fullwidth">
                    Incomes
                </button>
            </a>
        </div>
        <div class="block">
            <a href="{% url 'money_keeper_app:expense_list' account.id %}">
                <button class="button is-info is-fullwidth">
                    Expenses
                </button>
            </a>
        </div>
    </div>
</div>

{% endblock content %}

money_keeper_app/templates/money_keeper_app/accounts_list.html
{% extends 'base.html' %}

{% block content %}
<div class="column ">
    {% for account in accounts %}
    <div class="block ">
        <div class="card">
            <div class="card-content ">
                <div class="columns">
                    <div class="column">
                        <div class="media">
                            <div class="media-content">
                                <p class="title is-5">
                                    Account: {{ account.account_name }}
                                </p>
                                <p class="title is-6 ">
                                    Amount: {{ account.amount }}
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="column">
                        <div class="block">
                            <a href="{% url 'money_keeper_app:account' account.id %}">
                                <button class="button is-info ">
                                    Open
                                </button>
                            </a>
                            <a href="{% url 'money_keeper_app:upd_account' account.id %}">
                                <button class="button is-info ">
                                    Update
                                </button>
                            </a>
                            <a href="{% url 'money_keeper_app:delete' account.id %}">
                                <button class="button is-info ">
                                    Delete
                                </button>
                            </a>
                        </div>
                        <div class="block ">
                            <a href="{% url 'money_keeper_app:add_income'  account.id %}">
                                <button class="button is-info ">
                                    Add income
                                </button>
                            </a>
                            <a href="{% url 'money_keeper_app:add_expense'  account.id %}">
                                <button class="button is-info ">
                                    Add expense
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="column is-one-third">
    <div class="box">
        <div class="block">
            <a href="{% url 'money_keeper_app:add_account' %}">
                <button class="button is-info is-fullwidth">
                    Add account
                </button>
            </a>
        </div>
        <div class="block">
            <a href="{% url 'money_keeper_app:show_income_types' %}">
                <button class="button is-info is-fullwidth">
                    Show income types
                </button>
            </a>
        </div>
        <div class="block">
            <a href="{% url 'money_keeper_app:show_expense_types' %}">
                <button class="button is-info is-fullwidth">
                    Show expense types
                </button>
            </a>
        </div>
    </div>
</div>

{% endblock content %}

money_keeper_app/templates/money_keeper_app/add_account.html
{% extends 'base.html' %}

{% block content %}

<div class="column is-one-third">
    <div class="box">
        <div class="block">
            <p class="title is-2">
                Add account
            </p>
        </div>
        <div class="block">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="button is-info is-fullwidth is-normal mt-5" type="submit">
                    Add account
                </button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

money_keeper_app/templates/money_keeper_app/add_expense.html
{% extends 'base.html' %}

{% block content %}

<div class="column is-one-third">
    <div class="box">
        <div class="block">
            <p class="title is-2">
                Add expense
            </p>
        </div>
        <div class="block ">
            <form method="post" >
                {% csrf_token %}
                {{ form.as_p }}
                <button class="button is-info is-fullwidth is-normal mt-5" type="submit">
                    Add expense
                </button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

money_keeper_app/templates/money_keeper_app/income_list.html
{% extends 'base.html' %}

{% block content %}

<div class="column">
    <div class="block">
        <div class="card">
            <div class="card-content">
                <div class="columns">
                    <div class="column">
                        <div class="media">
                            <div class="media-content">
                                <p class="title is-5">
                                    Account: {{ account.account_name }}
                                </p>
                                <p class="title is-6">
                                    Amount: {{ account.amount }}
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="column">
                        <a href="{% url 'money_keeper_app:upd_account' account.id %}">
                            <button class="button is-info ">
                                Update
                            </button>
                        </a>
                        <a href="{% url 'money_keeper_app:add_income'  account.id %}">
                            <button class="button is-info ">
                                Add income
                            </button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="block">
        {% for income in incomes %}
            <div class="card">
                <div class="card-content">
                    <div class="media">
                        <div class="media-content">
                            <div class="columns">
                                <div class="column">
                                    <p class="title is-5">
                                        Income: +{{ income.count }} ({{income.created_at}})
                                    </p>
                                    <p class="title is-6">
                                        {{ income.income }}
                                    </p>
                                </div>
                                <div class="column">
                                    <a href="{% url 'money_keeper_app:upd_income' account.id income.pk %}">
                                        <button class="button is-info ">
                                            Update income
                                        </button>
                                    </a>
                                    <a href="{% url 'money_keeper_app:delete_income'  account.id income.pk %}">
                                        <button class="button is-info ">
                                            Delete income
                                        </button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

<div class="column is-one-third">
    <div class="box">
        <div class="block">
            <a href="{% url 'money_keeper_app:account' account.id %}">
                <button class="button is-info is-fullwidth">
                    All payments
                </button>
            </a>
        </div>
        <div class="block">
            <a href="{% url 'money_keeper_app:income_list' account.id %}">
                <button class="button is-info is-outlined is-fullwidth">
                    Incomes
                </button>
            </a>
        </div>
        <div class="block">
            <a href="{% url 'money_keeper_app:expense_list' account.id %}">
                <button class="button is-info is-fullwidth">
                    Expenses
                </button>
            </a>
        </div>
    </div>
</div>

{% endblock content %}